version: "2"      # required to adjust maintainability checks
checks:
  similar-code:
    enabled: false
  identical-code:
    enabled: false
    
plugins:
  pep8:
    enabled: true
  pylint:
    enabled: true
  sonar-python:
    enabled: true
  radon:
    enabled: true
