# The name of the workflow
name: build

# What conditions trigger the workflow
#  In this case, all pushes and pull requests
on: [push, pull_request]

# The jobs that will be run, usually in parallel
jobs:
  # A job to generate and publish code coverage
  coverage:
    name: Test and publish test coverage
    # The OS on which the job will run
    runs-on: ubuntu-latest

    # The steps for the job, executed in sequence
    steps:

      # A GitHub action for checking out the current branch
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8

      - name: Run unit tests
        run:
          pip install pytest
          pytest

      # A GitHub action to setup Node.js
      - uses: actions/setup-node@master
        with:
          node-version: "12"

      # Run the coverage install command before proceeding
      - run: pip install coverage

      # A GitHub action for running tests and publishing coverage
      - uses: fedora-python/tox-github-action
        tox_env: py38
        
      #    # An environment variable, the value is a GitHub repo secret
          CC_TEST_REPORTER_ID: ${{ secrets.CodeClimateReporterId }}
       # with:
          # Run our tests in our test.py
          coverageCommand: coverage run test.py
          # By default, this looks for a `coverage` folder in the root of your project, but you may need to change this
          coverageLocations: "./coverage/clover.xml:clover"
          # Great for troubleshooting
          debug: true
