# The name of the workflow
name: build

# What conditions trigger the workflow
#  In this case, all pushes and pull requests
on: [push, pull_request]

# The jobs that will be run, usually in parallel
jobs:
  # A job to generate and publish code coverage
  coverage:
    name: Test and publish test coverage
    # The OS on which the job will run
    runs-on: ubuntu-latest

    # The steps for the job, executed in sequence
    steps:

      # A GitHub action for checking out the current branch
      - uses: actions/checkout@master
      
      - name: Set up Python
        uses: actions/setup-python@master
        with: 
          python-version: 3.8
      
      - name: Run unit tests
        run: 
          pip install pytest
          pytest
      
      
    #  - name: intall requirements.txt
     #   run: pip install -r requirements.txt
        
      - name: Code Climate Coverage Action
      - uses: paambaati/codeclimate-action@v2.3.0
        #if: matrix.py_ver == '3.7'
        env:
          CC_TEST_REPORTER_ID: 05f6288b94a87daa172d3e96a33ec331a4374be7d01eb9a42b3b21c4c550a8ff
        with:
          coverageCommand: coverage xml
          debug: true
        
      

      # A GitHub action to setup Node.js
      #- uses: actions/setup-node@master
      #  with:
      #    node-version: "12"

      # Run the NPM install command before proceeding
      #- run: npm install

      # A GitHub action for running tests and publishing coverage
      #- uses: paambaati/codeclimate-action@v2.4.0
       # env:
      #    # An environment variable, the value is a GitHub repo secret
        #  CC_TEST_REPORTER_ID: ${{ secrets.CodeClimateReporterId }}
       # with:
          # Run our `coverage` script in our `package.json`
          #coverageCommand: npm run test:CI
          # By default, this looks for a `coverage` folder in the root of your project, but you may need to change this
         # coverageLocations: "./coverage/clover.xml:clover"
          # Great for troubleshooting
          #debug: true
